version: '3.8'

services:
  prohappy-assignments:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prohappy-assignments-web
    ports:
      - "80:80"
    environment:
      # Webhook URLs - replace with your actual n8n instance URLs
      - VITE_ASSIGNMENT_WEBHOOK_URL=${VITE_ASSIGNMENT_WEBHOOK_URL:-https://your-n8n-instance.com/webhook/assignment}
      - VITE_CHANGES_WEBHOOK_URL=${VITE_CHANGES_WEBHOOK_URL:-https://your-n8n-instance.com/webhook/changes}
      - VITE_WORKER_WEBHOOK_URL=${VITE_WORKER_WEBHOOK_URL:-https://your-n8n-instance.com/webhook/worker}
      
      # File upload configuration
      - VITE_FILE_UPLOAD_MAX_SIZE=${VITE_FILE_UPLOAD_MAX_SIZE:-10485760}
      
      # Environment
      - VITE_ENVIRONMENT=${VITE_ENVIRONMENT:-production}
      
      # Optional integrations
      - VITE_ANALYTICS_ID=${VITE_ANALYTICS_ID:-}
      - VITE_SENTRY_DSN=${VITE_SENTRY_DSN:-}
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health.json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prohappy.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.prohappy.tls=true"
      - "traefik.http.routers.prohappy.tls.certresolver=letsencrypt"
      - "traefik.http.services.prohappy.loadbalancer.server.port=80"

networks:
  default:
    name: prohappy-network